export const SET_STAGE = "SET_STAGE"
export const SET_LEVEL = "SET_LEVEL"
export const LOAD_GAME = "LOAD_GAME"
export const SET_PCS = "SET_PCS"
export const SET_ACTIVE_PCS = "SET_ACTIVE_PCS"
export const ADD_LOG_ENTRY = "ADD_LOG_ENTRY"
export const SET_CHARACTER_INITIATIVE = 'SET_CHARACTER_INITIATIVE'
export const ORDER_CHARACTER_BY_INITIATIVE = 'ORDER_CHARACTER_BY_INITIATIVE' 
